### ISSUE TITLE
Individuelles Template

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-navigation_plus#1]
Hallo, kann dem Modul ein "Individuelles Template" zugeordnet werden. Leider kann ich im Backend keins auswählen. Ich müsste dieses anpassen um die Struktur der Navigation anzupassen.

**Comment by fatcrobat** [comment]
Ther should be a navigationTpl dropdown where you can change the used navigation template.

**Comment by operatorone** [comment]
Nope. There is none! [https://ibb.co/Mg3g3JL](url)

**Comment by fatcrobat** [comment]
Copy mod_navigation.html5 to templates /templates/mod_navigation_custom.html5 and there should be one.

**Comment by operatorone** [comment]
Thanks. That did it.
